message( STATUS "------------------------------------------------------------------" )
message( STATUS "HOST System Name:  ${CMAKE_HOST_SYSTEM_NAME}" )
message( STATUS "HOST System:       ${CMAKE_HOST_SYSTEM}" )
message( STATUS "CMake Generator:   ${CMAKE_GENERATOR}" )
if (WIN32)
message( STATUS "Runtime Library:   ${CMAKE_MSVC_RUNTIME_LIBRARY}" )
endif()
if (CMAKE_GENERATOR STREQUAL "Visual Studio 16 2019")
message( STATUS "CMake VS toolset host arch:   ${CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE}" )
message( STATUS "CMAKE_GENERATOR_PLATFORM:   ${CMAKE_GENERATOR_PLATFORM}" )
endif()
message( STATUS "CMAKE_BUILD_TYPE:  ${CMAKE_BUILD_TYPE}" )
message( STATUS "Compiler info: ${CMAKE_C_COMPILER_ID} (${CMAKE_C_COMPILER}) ; version: ${CMAKE_C_COMPILER_VERSION}")
message( STATUS " --- Compiler flags --- ")
message( STATUS "Custom compiler options: " )
message( STATUS "General:           ${CMAKE_C_FLAGS}" )
message( STATUS "Debug:             ${CMAKE_C_FLAGS_DEBUG}" )
message( STATUS "Release:           ${CMAKE_C_FLAGS_RELEASE}" )
message( STATUS "" )
message( STATUS " --- Global CMake Options --- ")
message( STATUS "BUILD_SHARED_LIBS: ${BUILD_SHARED_LIBS}" )
message( STATUS "CMAKE_INSTALL_PREFIX: ${CMAKE_INSTALL_PREFIX}" )
message( STATUS "" )
message( STATUS " --- Project specific Options --- ")
message( STATUS "BUILD_UNIT_TESTS:  ${BUILD_UNIT_TESTS}" )
message( STATUS "" )
